## 080120_PR NUMPY

In [2]:
import numpy as np

#### SOAL 1

In [2]:
# np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### OUTPUT

In [6]:
# -1 pada kolom atau row artinya menyesuaikan sendiri jumlah kolom atau row
# np.arange(10).reshape(-1,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### SOAL 2

In [7]:
# arr = np.arange(4,13).reshape(3,3)
# arr

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

#### OUTPUT

In [15]:
# arr[0][0], arr[0][1] = arr[0][1],arr[0][0]
# arr[1][0], arr[1][1] = arr[1][1],arr[1][0]
# arr[2][0], arr[2][1] = arr[2][1],arr[2][0]
# arr

# # CARA SINGKAT
# arr [:,[1,0,2]]

array([[ 5,  4,  6],
       [ 8,  7,  9],
       [11, 10, 12]])

#### SOAL 3

In [4]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### OUTPUT

In [5]:
new_array = np.array([arr[2],arr[1],arr[0]])
new_array

# # CARA LAIN
# arr[:,::-1] 

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

#### SOAL 4

In [6]:
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])
array_of_arrays

array([array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])],
      dtype=object)

#### OUTPUT

In [7]:
new = np.concatenate([arr1,arr2,arr3])
new

# # CARA LAIN
arr = np.array([i for ar in array_of_arrays for i in ar])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])